name: Run master pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests numpy seaborn matplotlib flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run master workflow
      run: |
        set -e
        python workflow.py

    - name: Upload all outputs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: full-pipeline-outputs
        path: |
          results/analysis/
          data/raw/
          data/processed/
          data/db/
          data/checksums.json
